-- Nick Farkas
USE [master]
GO
/****** Object:  Database [Assignment5]    Script Date: 12/11/2019 12:31:13 AM ******/
CREATE DATABASE [Assignment5]
GO
ALTER DATABASE [Assignment5] SET COMPATIBILITY_LEVEL = 140
GO
ALTER DATABASE [Assignment5] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Assignment5] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Assignment5] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Assignment5] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Assignment5] SET ARITHABORT OFF 
GO
ALTER DATABASE [Assignment5] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Assignment5] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Assignment5] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Assignment5] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Assignment5] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Assignment5] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Assignment5] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Assignment5] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Assignment5] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Assignment5] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Assignment5] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Assignment5] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Assignment5] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Assignment5] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Assignment5] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Assignment5] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Assignment5] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Assignment5] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Assignment5] SET  MULTI_USER 
GO
ALTER DATABASE [Assignment5] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Assignment5] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Assignment5] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Assignment5] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Assignment5] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Assignment5] SET QUERY_STORE = OFF
GO
USE [Assignment5]
GO
/****** Object:  Table [dbo].[Bowler]    Script Date: 12/11/2019 12:31:13 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Bowler](
	[TeamNo] [int] NOT NULL,
	[PlayerNo] [int] NOT NULL,
	[PhoneNo] [varchar](10) NULL,
	[Gender] [int] NULL,
	[TeamName] [varchar](50) NULL,
	[Captain] [varchar](50) NULL,
	[Email] [varchar](50) NULL,
 CONSTRAINT [PK_Bowler] PRIMARY KEY CLUSTERED 
(
	[PlayerNo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Scores]    Script Date: 12/11/2019 12:31:13 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Scores](
	[PlayerNo] [int] NOT NULL,
	[WeekNo] [int] NOT NULL,
	[Score1] [int] NULL,
	[Score2] [int] NULL,
	[Score3] [int] NULL,
 CONSTRAINT [PK_Scores] PRIMARY KEY CLUSTERED 
(
	[PlayerNo] ASC,
	[WeekNo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TeamInfo]    Script Date: 12/11/2019 12:31:13 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TeamInfo](
	[TeamNo] [int] NOT NULL,
	[TeamName] [varchar](50) NULL,
	[Captain] [int] NULL,
 CONSTRAINT [PK_TeamInfo] PRIMARY KEY CLUSTERED 
(
	[TeamNo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Bowler]  WITH CHECK ADD  CONSTRAINT [FK_TeamNo] FOREIGN KEY([TeamNo])
REFERENCES [dbo].[TeamInfo] ([TeamNo])
GO
ALTER TABLE [dbo].[Bowler] CHECK CONSTRAINT [FK_TeamNo]
GO
ALTER TABLE [dbo].[Scores]  WITH CHECK ADD  CONSTRAINT [FK_PlayerNo] FOREIGN KEY([PlayerNo])
REFERENCES [dbo].[Bowler] ([PlayerNo])
GO
ALTER TABLE [dbo].[Scores] CHECK CONSTRAINT [FK_PlayerNo]
GO
ALTER TABLE [dbo].[TeamInfo]  WITH CHECK ADD  CONSTRAINT [FK_Captain] FOREIGN KEY([Captain])
REFERENCES [dbo].[Bowler] ([PlayerNo])
GO
ALTER TABLE [dbo].[TeamInfo] CHECK CONSTRAINT [FK_Captain]
GO
ALTER TABLE [dbo].[Bowler]  WITH CHECK ADD  CONSTRAINT [CK_Gender] CHECK  (([Gender]=(1) OR [Gender]=(2)))
GO
ALTER TABLE [dbo].[Bowler] CHECK CONSTRAINT [CK_Gender]
GO
USE [master]
GO
ALTER DATABASE [Assignment5] SET  READ_WRITE 
GO